	  SUBROUTINE PDSENS(KENS,KPROB,XPROB,KCLUST,KMEMBR,ILAST,MSGA)
	  INTEGER KENS(5),KPROB(2),KCLUST(16),KMEMBR(80)
      REAL*8 XPROB(2)
      DIMENSION SXPROB(2)
	  CHARACTER*1 MSGA(100)
	  IF(ILAST.LT.41) THEN
	  PRINT *,'WARNING - SUBROUTINE IS FOR PACKING BYTES 41 AND ABOVE'
	  GO TO 333
	  ENDIF
C	PACKING IS DONE IN FOUR SECTIONS ENDING AT BYTE IL
	  IF(ILAST.GE.41) IL=45
	  IF(ILAST.GE.46) IL=55
	  IF(ILAST.GE.61) IL=76
	  IF(ILAST.GE.77) IL=86
C	CHANGING THE NUMBER OF BYTES (FIRST THREE BYTES IN PDS)
      CALL SBYTE(MSGA, IL, 0,24)
C	PACKING FIRST SECTION (GENERAL INTORMATION SECTION)
      IF(IL.GE.45) CALL SBYTES(MSGA,KENS,40*8,8,0,5)
C	PACKING 2ND SECTION (PROBABILITY SECTION)
      IF(IL.GE.55) THEN
          CALL SBYTES(MSGA,KPROB,45*8,8,0,2)
	  CALL W3FI01(LW)
      SXPROB(1)=XPROB(1)
	  CALL W3FI76(SXPROB(1),IEXP,IMANT,8*LW)
          CALL SBYTE(MSGA,IEXP,47*8,8)
          CALL SBYTE(MSGA,IMANT,48*8,24)
      SXPROB(2)=XPROB(2)
	  CALL W3FI76(SXPROB(2),IEXP,IMANT,8*LW)
          CALL SBYTE(MSGA,IEXP,51*8,8)
          CALL SBYTE(MSGA,IMANT,52*8,24)
      ENDIF
C	PACKING 3RD SECTION (CLUSTERING INFORMATION)
      IF(IL.GE.76) CALL SBYTES(MSGA,KCLUST,60*8,8,0,16)
C	PACKING 4TH SECTION (CLUSTER MEMBERSHIP)
      IF(IL.GE.86) CALL SBYTES(MSGA,KMEMBR,76*8,1,0,10)
C
 333  CONTINUE
	  RETURN
	  END
