#!/bin/sh
if [ -z "$model_res_area" ] ; then
	res_num_existx=\$res_num_exist_$count
	res_num_existx=`eval echo $res_num_existx`
	if [ -z "$res_num_existx" ] ; then
		if [ "$runscript" = gsmrt ] ; then
			res_num_existx=4
		else
			res_num_existx=3
		fi
	fi
fi
ls -1d ./def/def_crsm/crsm*  | sed 's%.*/%%g' >out.$$
nn=`wc -l out.$$ | awk '{print $1}'`
echo " "
echo "Model resolution and domain specification"
n=1
while [ $n -le $nn ] ; do
	echo "($n) `sed -n "$n"p out.$$`"
	n=`expr $n + 1`
done
if [ "$continue" != yes ] ; then
	echo "Type the number associated with your model dimension specification."
	echo -n "If there is no choice available, type 999 [return=$res_num_existx] ==>"
	read num
else
	num=
fi
if [ -z "$num" ] ; then
	num=$res_num_existx
elif [ "$num" -eq 999 ] ; then
	echo "1. create crsmIGRDxJGRD_gGRESkVRES_DOM_HKMkm_PROJ_rCIGRDxCJGRD_CDOM_CHKMkm_CPRJ directory in def_crsm"
	echo "  where IGRD is regional model x-dimension (e.g. 81)"
	echo "        JGRD is regional model y-dimension (e.g. 87)"
	echo "        GRES is global model dimension (e.g. 62)"
	echo "        VRES is number of levels in the vertical (e.g. 28)"
	echo "        CIGRD is coarse res regional model x-dimension (e.g. 81)"
	echo "        CJGRD is coarse res regional model y-dimension (e.g. 87)"
	echo "        DOM  is a neme of the domain (e.g. usa)"
	echo "        HKM  is regional model grid distance in km"
	echo "        PROJ is regional model map projection [merc/str]"
	echo "        CDOM is a coase res name of the domain (e.g. usa)"
	echo "        CHKM is coarse res model grid distance in km"
	echo "        CPRJ is coarse res model map projection [merc/str]"
	echo "2. In that directory, create define.h, modlsigs.h,"
	echo "     postplevs.h, DOM_IGRDxJGRD_HKMkm_PROJ.h and"  
	echo "     CDOM_CIGRDxCJGRD_CHKMkm_CPRJ.h files"  
	echo "     Just copy first 3 files from other directory"
	echo "     and modify.  It is usually sufficient to change"
	echo "     _igrd_, and _jgrd_ in define.h"
	echo "3. for DOM_IGRDxJGRD_HKMkm_PROJ.h and"
	echo "       CDOM_CIGRDxCJGRD_CHKMkm_CPROJ.h refer to other domain"
	echo "     specification files. Use prmap to plot the area"
	echo "     using grads"
	echo "4. ./install again"
	rm out.$$
	exit
fi
MODEL_DEFINE=`sed -n "${num}p" out.$$`
rm out.$$
eval res_num_$count=$num
res_numx=\$res_num_$count
res_numx=`eval echo $res_numx`
if [ -z "$res_numx" ] ; then
	eval res_num_$count=$res_num_existx
fi
res_numx=\$res_num_$count
res_numx=`eval echo $res_numx`
eval res_$count=$MODEL_DEFINE
