#!/bin/sh
uname=`uname`
echo $uname | grep -i LINUX >/dev/null 
if [ $? -eq 0 ] ; then 
	MACHINE=linux 
	echo `hostname` | grep -i 'shigoto' >/dev/null
	if [ $? -eq 0 ] ; then
		MACHINE=sx6 
	fi
fi 
echo $uname | grep -i AIX >/dev/null 
if [ $? -eq 0 ] ; then 
	MACHINE=ibmsp 
fi 
echo $uname | grep -i OSF >/dev/null 
if [ $? -eq 0 ] ; then
	MACHINE=dec
fi
echo $uname | grep -i IRIX >/dev/null
if [ $? -eq 0 ] ; then
	MACHINE=sgi
fi
echo $uname | grep -i SUPER >/dev/null
if [ $? -eq 0 ] ; then
	MACHINE=nec
fi
echo $uname | grep -i HP-UX >/dev/null
if [ $? -eq 0 ] ; then
	MACHINE=es
fi
echo $uname | grep -i ESOS >/dev/null
if [ $? -eq 0 ] ; then
	MACHINE=es
fi
echo $uname | grep -i Darwin >/dev/null
if [ $? -eq 0 ] ; then
	MACHINE=mac
fi
if [ -z "$MACHINE" ] ; then
	echo -n "cannot identify this MACHINE.  type in MACHINE name.==>"
	read MACHINE
	if [ "$MACHINE" !=  sgi -a \
			"$MACHINE" !=  mac -a \
			"$MACHINE" !=  origin -a \
			"$MACHINE" !=  ibmsp -a \
			"$MACHINE" !=  sun -a \
			"$MACHINE" !=  dec -a \
			"$MACHINE" !=  nec -a \
			"$MACHINE" !=  hp -a \
			"$MACHINE" !=  cray -a \
			"$MACHINE" !=  t90 -a \
			"$MACHINE" !=  t3e -a \
			"$MACHINE" !=  es -a \
			"$MACHINE" !=  linux ] ; then
		echo $MACHINE not available.  try MACHINE as linux
		MACHINE=linux
	fi
fi
#
mach=
if [ -s .hist ] ; then
	mach=`grep "^MACHINE=" .hist | cut -d"=" -f2`
fi
if [ -z "$mach" ] ; then
	mach=$MACHINE
fi
if [ "$continue" != yes ] ; then
	echo ' '
	echo 'Machine CPU type'
	echo -n "Type MACHINE,  ? for list [return=$MACHINE].==>"
	read mach
else
	mach=
fi
if [ "$mach" = '?' ] ; then
	echo -n "sgi origin ibmsp sun dec nec hp cray t90 t3e es linux mac ==>"
	read mach
fi
if [ ! -z "$mach" ] ; then
	machine=$mach
fi
grep MACHINE= .hist >/dev/null 2>/dev/null
rc=$?
sed "s/MACHINE=.*/MACHINE=$MACHINE/g" .hist >tmp.$$
if [ $rc -eq 0 ] ; then
	mv tmp.$$ .hist	
else
	echo MACHINE=$MACHINE >>.hist
fi
#
