#!/bin/sh
#
NICKNAME=`hostname | cut -d'.' -f1`
#
echo "$NICKNAME" | grep nid00 >/dev/null 2>/dev/null
if [ $? -eq 0 ] ; then
	NICKNAME=franklin
fi
#
if [ -s .hist ] ; then
        nickname=`grep "^NICKNAME=" .hist | cut -d'=' -f2`
fi
if [ -z "$nickname" ] ; then
	nickname=$NICKNAME
fi
if [ "$continue" != yes ] ; then
	echo ' '
	echo "Machine nickname"
	echo -n "Type the machine nickname [return=$NICKNAME] ==>"
	read name
else
	name=
fi
if [ -z $name ] ; then
	NICKNAME=$NICKNAME
else
	NICKNAME=$name 
fi
grep NICKNAME= .hist >/dev/null 2>/dev/null
rc=$?
sed "s/NICKNAME=.*/NICKNAME=$NICKNAME/g" .hist >tmp.$$
if [ $rc -eq 0 ] ; then
	mv tmp.$$ .hist	
else
	echo NICKNAME=$NICKNAME >>.hist
fi
