#!bin/sh
#
#  This script creates bourn shell script "mdlvars" which defines variables defined 
#  in define.h file, and "mdlvars.sed" file for sed.
#
list_defines="machine.h define.h"
#
#  if rsm or roms, add domainspec variables to 
#
if [ -s "$MODEL_DEFINE/domainspec" ] ; then
	#
	#  convert domainspec bourn shell file to c-processor define file
	#
	sed '/^ *#/d
		s/^/_/g
		s/=/_=/g
		s/^.*=/\L&/g
		s/\. *$//g
		s/^/#define /g
		s/=/ /g' <$MODEL_DEFINE/domainspec >domainspec.h
	list_defines="machine.h domainspec.h define.h"
fi
cat $list_defines | \
	sed 's/^#define *//g
	s/^#undef *//g
	/#if/d
	/#endif/d
	/#else/d
	/#include/d
	s!/\*.*$!!g
	/^[ ]*$/d
	s/[	 ]*$//g
	/^ *#/d' | sort -u >tmp.$$
#
#cp tmp.$$ tmp
#
cat $list_defines >mdlvars.F
sed 's/ *$//g' tmp.$$| grep ' ' | \
	sed 's/ .*$//g' | sort -u | \
	sed 's/\(.*\)/\1=\1/g
	s/^_/@/g
	s/_=/@=/g
	s/\(.*\)=/%\L\1%=/g
	s/[ 	]*$//g' >>mdlvars.F
#
echo '#!/bin/sh' >mdlvars
echo 'set -x' >>mdlvars
echo '#' >>mdlvars
$CPP -P -I./ mdlvars.F | \
	sed '/^ *$/d
	s/\//#/g
	s/\!/#/g
	s/%@/_/g
	s/@%/_/g
	s/%.*%=/\U&/g
	s/^%//g
	s/%=/=/g
	s/[ 	]*$//g
	s/\(^.*\)=\1/\1=undefined/g' >>mdlvars
#
uname=`uname`
cat $list_defines >mdlvars_d.F
sed 's/[ 	]*$//g
	/ /d
	/^#/d
	s/\(.*\)/\1=\1/g
	s/.*=/\L&/g' tmp.$$  >>mdlvars_d.F
#
$CPP -P -I./ mdlvars_d.F | \
	sed '/^ *$/d
	s/\//#/g
	s/\!/#/g
	s/.*=/\U&/g
	s/=[^ ][^ ]*$/=undefined/g
	s/= *$/=DEFINED/g' | \
	sed "s/^[0-9].*=/$uname=/g" | \
	sort -u | sort -t'=' -k 2,2  >>mdlvars
#
chmod a+x mdlvars
rm tmp.$$ 
#rm mdlvars.F mdlvars_d.F
#
#  add configure-model generated variables
#
echo "MODEL=$MODEL" >>mdlvars
echo "MODEL_DEFINE=$MODEL_DEFINE" >>mdlvars
echo "MODEL_DIR=$MODEL_DIR" >>mdlvars
echo "ROMS_APPLICATION=$ROMS_APPLICATION" >>mdlvars
#
#  execute mdlvars to evaluate any variable assignment and calculations
#
./mdlvars 2>tmp.$$
#
#  create file for sed
#
grep '.*=' tmp.$$ | \
	sed 's/^++* //g
	s/^_[a-z0-9].*=/\U&/g
	s/^_//g
	s/\(.*=\)\(.*\)/s%@\1@%\2%g/g
	s/_=/=/g
	s/=//g
	s/undefined//g
	s/"//g' | sed "s/'//g" >mdlvars.sed
rm tmp.$$
sed '/set -x/d' mdlvars >tmp.$$
mv tmp.$$ mdlvars
chmod a+x mdlvars
