#!/bin/sh
#
if [ $# -ne 5 ] ; then
	echo 'Usage: grpgdsfix input_grib_file lonw lone lats latn'
	echo "`date` $0: Wrong usage." >>ERROR.out
	exit 8
fi
#
if [ ! -s $1 ] ; then
	echo "file $1 empty"
	exit 8
fi
#
dir=`echo $0 | sed 's?/[^/]*$??g'`
currdir=`pwd`
cd $dir 2>/dev/null
GRFIXDIR=`pwd`
cd $currdir
#
NO_STOP_MESSAGE=true
export NO_STOP_MESSAGE
#
cat << EOF | $GRFIXDIR/grpgdsfix.x
 &namin
 fngrib="$1"
 rlonw=$2
 rlone=$3
 rlats=$4
 rlatn=$5
/
EOF
if [ $? -ne 0 ] ; then
	echo "`date` $0: Execution failed."
	exit 8
fi
