#!/bin/sh
#
set -x
if [ $# -ne 1 -a $# -ne 2 ] ; then
  echo "Usage: prmap [runscript domaindir] [C]"
  exit 8
fi
dir=$1
RorC=$2
if [ -z "$RorC" ] ; then
	RorC=R
fi
#
file=$dir/domainspec
RPROJ=`grep "^${RorC}PROJ=" $file | cut -d"=" -f2`
RTRUTH=`grep "^${RorC}TRUTH=" $file | cut -d"=" -f2`
RORIENT=`grep "^${RorC}ORIENT=" $file | cut -d"=" -f2`
RDELX=`grep "^${RorC}DELX=" $file | cut -d"=" -f2`
RDELY=`grep "^${RorC}DELY=" $file | cut -d"=" -f2`
RCENLAT=`grep "^${RorC}CENLAT=" $file | cut -d"=" -f2`
RCENLON=`grep "^${RorC}CENLON=" $file | cut -d"=" -f2`
RLFTGRD=`grep "^${RorC}LFTGRD=" $file | cut -d"=" -f2`
RBTMGRD=`grep "^${RorC}BTMGRD=" $file | cut -d"=" -f2`
#
file=$dir/define.h
IGRD=`grep '#define _igrd_ ' $file | awk '{print $3}'`
JGRD=`grep '#define _jgrd_ ' $file | awk '{print $3}'`
IGRD1=`expr $IGRD + 1`
JGRD1=`expr $JGRD + 1`
#
cat >prmap.parm <<EOF
 &namloc
 IGRD1=$IGRD1
 JGRD1=$JGRD1
 RPROJ=$RPROJ
 RTRUTH=$RTRUTH
 RORIENT=$RORIENT
 RDELX=$RDELX
 RDELY=$RDELY
 RCENLAT=$RCENLAT
 RCENLON=$RCENLON
 RLFTGRD=$RLFTGRD
 RBTMGRD=$RBTMGRD
 &end
EOF
#
dir=`echo $0 | sed 's?/[^/]*$??g'`
currdir=`pwd`
cd $dir
PRMAPDIR=`pwd`
echo "PRMAPDIR=$PRMAPDIR"
export PRMAPDIR
cd $currdir
#
$PRMAPDIR/prmap.x <prmap.parm 2>stderr$$.prmap
cc=$?
if [ $cc -ne 0 ] ; then
  echo ' prmap execution failed'
  exit 8
fi
rm stderr$$.prmap
gradsc -l -c "open prmap.ctl"
