#!/bin/sh
#
#  print out rms difference of two r_sig files
#
set -x
if [ $# -ne 5 ] ; then
  echo "Usage: rsigdiff file1 file2 levs idim jdim"
  exit 8
fi
#
cat >rsigdiff <<EOF
 &namin
 FILE1='$1',
 FILE2='$2',
 LEVS=$3,
 IDIM=$4,
 JDIM=$4,
 &end
EOF
#
dir=`echo $0 | sed 's?/[^/]*$??g'`
currdir=`pwd`
cd $dir
rsigdiffdir=`pwd`
echo "rsigdiffdir=$rsigdiffdir"
cd $currdir
#
$rsigdiffdir/rsigdiff.x <rsigdiff 2>stderr$$.rsigdiff
cc=$?
if [ $cc -ne 0 ] ; then
  echo ' rsigdiff execution failed'
  exit 8
fi
rm stderr$$.rsigdiff
