#!/bin/sh
#
#  blocking
#
INPUT_BUFR_BLOCKING=$1
input_bufr_file_name=$2
outfile=$3
#
if [ $INPUT_BUFR_BLOCKING = no ] ; then
	PROG=bufrblock
	rm $outfile 2>/dev/null
	/rhome/yeong/test/svrtest/libs/etc/bufrblk $input_bufr_file_name $outfile linux
	if [ $? -ne 0 ] ; then
		echo "blocking execution failed" >>ERROR.out
		exit 8
	fi
elif [ $INPUT_BUFR_BLOCKING = linux ] ; then
	cp $input_bufr_file_name $outfile
	if [ $? -ne 0 ] ; then
		echo "copy prepbufr failed" >>ERROR.out
		exit 8
	fi
else
	echo input bufr blocking inconsistent with this machine >>ERROR.out
	exit 8
fi
