#!/bin/sh
#
PROG=combbufr
echo `date` -- $PROG started  >>ERROR.out
rm combbufr_bufr_output 2>/dev/null
if [ linux = cray -o linux = t90 -o linux = t3e ] ; then
	assign -R
	assign -a bufr_sfcsat             -Fcos fort.20
	assign -a bufr_adpupa_cqc_output  -Fcos fort.21
	assign -a bufr_aircft_acqc_output -Fcos fort.22
	assign -a combbufr_bufr_output    -Fcos fort.50
else
	rm -f fort.[0-9]* 2>/dev/null
	ln -fs bufr_sfcsat             fort.20
	ln -fs bufr_adpupa_cqc_output  fort.21
	ln -fs bufr_aircft_acqc_output fort.22
	ln -fs combbufr_bufr_output    fort.50
fi
if [ linux = cray -o linux = t90 -o linux = t3e ] ; then
	NCPUS=1
	export NCPUS
fi
#
echo 3 >$PROG.parm
#
rm -f $PROG.x
ln -fs /rhome/yeong/test/svrtest/gsm/bin/${PROG}.x $PROG.x
./$PROG.x <$PROG.parm 1>$PROG.out 2>&1
if [ $? -ne 0 ] ; then
	echo "`date` $0: Execution failed." >>ERROR.out
	exit 8
fi
if [ linux != cray -a linux != t90 -o linux != t3e ] ; then
	rm -f fort.[0-9]* 2>/dev/null
fi
