#!/bin/sh
#
cqcbufr_minus_oneday=$1
cqcbufr_minus_hlfday=$2
cqcbufr_plus_hlfday=$3
cqcbufr_plus_oneday=$4
#
PROG=cqc
echo `date` -- $PROG started  >>ERROR.out
#
#  Time continuity check files
#
timecheck=yes
if [ ! -s $cqcbufr_minus_oneday ] ; then
	timecheck=no
	echo "Warning: cqcbufr minus one day file not found" >>ERROR.out
else
	filefmt1='-Fcos'
fi
if [ $timecheck = yes ] ; then
	if [ ! -s $cqcbufr_minus_hlfday ] ; then
		timecheck=no
		echo "Warning: cqcbufr minus half day file not found" >>ERROR.out
	else
		filefmt2='-Fcos'
	fi
fi
if [ $timecheck = yes ] ; then
	if [ ! -s $cqcbufr_plus_hlfday ] ; then
		timecheck=no
		echo "Warning: cqcbufr plus half day file not found" >>ERROR.out
	else
		filefmt3='-Fcos'
	fi
fi
if [ $timecheck = yes ] ; then
	if [ ! -s $cqcbufr_plus_oneday ] ; then
		timecheck=no
		echo "Warning: cqcbufr plus one day file not found" >>ERROR.out
	else
		filefmt4='-Fcos'
	fi
fi
#
#  Disable time check if any one of the four files is missing
#
if [ $timecheck = no ] ; then
	> empty1
	> empty2
	> empty3
	> empty4
	cqcbufr_minus_oneday='empty1'
	cqcbufr_minus_hlfday='empty2'
	cqcbufr_plus_hlfday='empty3'
	cqcbufr_plus_oneday='empty4'
	filefmt1=''
	filefmt2=''
	filefmt3=''
	filefmt4=''
fi
rm cqe.anl.ascii  cqb.anl.ascii  cqt.anl.ascii  2>/dev/null
#
list_blank_file="cqc11 cqc13 cqc16 cqe.anl.ascii cqb.anl.ascii"
for blank in $list_blank_file
do
   if [ ! -s $blank ] ; then
      > $blank
   fi
done
#
#  temporally disable time check
#
#if [ $DISABLE_CQC_TIME_CHECK = yes ] ; then
#	> empty1
#	> empty2
#	> empty3
#	> empty4
#	cqcbufr_minus_oneday='empty1'
# 	cqcbufr_minus_hlfday='empty2'
#	cqcbufr_plus_hlfday='empty3'
#	cqcbufr_plus_oneday='empty4'
#	filefmt1=''
#	filefmt2=''
#	filefmt3=''
#	filefmt4=''
#fi
#
if [ linux = cray -o linux = t90 -o linux = t3e ] ; then
	NCPUS=1
	export NCPUS
	assign -R
	assign -a bufr_adpupa -Fcos               fort.14
	assign -a $cqcbufr_minus_oneday $filefmt1 fort.17
	assign -a $cqcbufr_minus_hlfday $filefmt2 fort.18
	assign -a $cqcbufr_plus_hlfday  $filefmt3 fort.19
	assign -a $cqcbufr_plus_oneday  $filefmt4 fort.20
	assign -a bufr_adpupa_cqc_output -Fcos    fort.51
	assign -a cqc11                           fort.11
	assign -a cqe.anl.ascii                   fort.12
	assign -a cqc13                           fort.13
	assign -a cqb.anl.ascii                   fort.15
	assign -a cqc16                           fort.16
	assign -a cqt.anl.ascii                   fort.60
	assign -a cqc61                           fort.61
	assign -a cqc62                           fort.62
	assign -a cqc64                           fort.63
	assign -a cqc65                           fort.64
else
	rm -f fort.[0-9]* 2>/dev/null
	ln -fs bufr_adpupa            fort.14
	ln -fs $cqcbufr_minus_oneday  fort.17
	ln -fs $cqcbufr_minus_hlfday  fort.18
	ln -fs $cqcbufr_plus_hlfday   fort.19
	ln -fs $cqcbufr_plus_oneday   fort.20
	ln -fs bufr_adpupa_cqc_output fort.51
	ln -fs cqc11                  fort.11
	ln -fs cqe.anl.ascii          fort.12
	ln -fs cqc13                  fort.13
	ln -fs cqb.anl.ascii          fort.15
	ln -fs cqc16                  fort.16
	ln -fs cqt.anl.ascii          fort.60
	ln -fs cqc61                  fort.61
	ln -fs cqc62                  fort.62
	ln -fs cqc64                  fort.63
	ln -fs cqc65                  fort.64
fi
if [ linux = cray -o linux = t90 -o linux = t3e ] ; then
	NCPUS=1
	export NCPUS
fi
rm -f $PROG.x
ln -fs /rhome/yeong/test/svrtest/gsm/bin/${PROG}.x $PROG.x
./$PROG.x 1>$PROG.out 2>&1
if [ $? -ne 0 ] ; then
	echo "`date` $0: Execution failed." >>ERROR.out
	exit 8
fi
if [ linux != cray -a linux != t90 -o linux != t3e ] ; then
	rm -f fort.[0-9]* 2>/dev/null
fi
grep 'STOP INPUT - NO DATA' $PROG.out >/dev/null
if [ $? -eq 0 ] ; then
	echo ' ' >cqe.anl.ascii
	echo ' ' >cqt.anl.ascii
	echo ' ' >cqb.anl.ascii
else
	if [ ! -s cqe.anl.ascii ] ; then
		if [ -s cqt.anl.ascii ] ; then
			echo ' ' >cqe.anl.ascii
		fi
	fi
fi
