#!/bin/sh
#
yyyymmddhh=$1
YYYY=$2
MMS=$3
#
PROG=edbuoy
if [ $yyyymmddhh -ge 1978120100 -a $yyyymmddhh -le 1979123118 ] ; then
	buoy_black_list=/rhome/yeong/test/svrtest/libs/con/blacklist_$YYYY$MMS.asc
	rm prepbuoy 2>/dev/null
	if [ linux = cray -o linux = t90 -o linux = t3e ] ; then
		assign -R
		assign -a out.bufr -Fcos   fort.20
		assign -a $buoy_black_list fort.21
		assign -a prepbuoy -Fcos   fort.50
		else
			rm -f fort.[0-9]* 2>/dev/null
			ln -fs out.bufr         fort.20
			ln -fs $buoy_black_list fort.21
			ln -fs prepbuoy         fort.50
		fi
	if [ linux = cray -o linux = t90 -o linux = t3e ] ; then
		NCPUS=1
		export NCPUS
	fi
	rm -f $PROG.x
  ln -fs /rhome/yeong/test/svrtest/gsm/bin/${PROG}.x $PROG.x
  ./$PROG.x 1>$PROG.out 2>&1
  if [ $? -ne 0 ] ; then
    echo "`date` $0: Execution failed." >>ERROR.out
    exit 8
  fi
	if [ linux != cray -a linux != t90 -o linux != t3e ] ; then
		rm -f fort.[0-9]* 2>/dev/null
	fi
	cp prepbuoy out.bufr
else
	echo $PROG execution skipped >>ERROR.out
fi
