#!/bin/sh
#
yyyymmddhh=$1
PROG=edswnd
if [ $yyyymmddhh -eq 1973123118 ] ; then
	rm prepswnd 2>/dev/null
	if [ linux = cray -o linux = t90 -o linux = t3e ] ; then
		assign -R
		assign -a out.bufr -Fcos  fort.20
		assign -a prepswnd -Fcos  fort.50
	else
		rm -f fort.[0-9]* 2>/dev/null
		ln -fs out.bufr  fort.20
		ln -fs prepswnd  fort.50
	fi
	elon=230
	wlon=350
	slat=-55
	nlat=55
	INPUT=edswnd.parm
		cat <<EOF >edswnd.parm
		$elon $wlon $slat $nlat
EOF
	if [ linux = cray -o linux = t90 -o linux = t3e ] ; then
		NCPUS=1
		export NCPUS
	fi
	rm -f $PROG.x
  ln -fs /rhome/yeong/test/svrtest/gsm/bin/${PROG}.x $PROG.x
  ./$PROG.x <$PROG.parm 1>$PROG.out 2>&1
  if [ $? -ne 0 ] ; then
    echo "`date` $0: Execution failed." >>ERROR.out
    exit 8
  fi
	if [ linux != cray -a linux != t90 -o linux != t3e ] ; then
		rm -f fort.[0-9]* 2>/dev/null
	fi
	cp prepswnd out.bufr
else
	echo $PROG execution skipped >>ERROR.out
fi
