#!/bin/sh
#
# vertical cordinate for boudary data reading latitude and longtiude from rsm
#
PROG=nhm_flonflat
rm fort.* 2>/dev/null
ln -fs $RSIG_DIR/r_sigit.ft00       fort.20
ln -fs ./flatflon_rsm.dat           fort.30
ln -fs ./mpab.txt                   fort.40
ln -fs $OUTER_RSM_SRCS_DIR/define.h fort.50
cat <<EOF >$PROG.parm
 &adnum
   iadd=$2
 &end
EOF
ln -fs /rhome/yeong/test/svrtest/gsm/bin/$PROG.x $PROG.x
./$PROG.x < ./$PROG.parm 1>$PROG.out 2>&1
if [ $? -ne 0 ] ; then
	echo "`date` $0: Execution failed." >>ERROR.out
	echo "`date` $0: Execution failed."
	exit 8
fi
