#!/bin/sh
#
# read rsm map data
#
PROG=nhm_read_location
rm fort.*
ln -fs $OUTER_RSM_SRCS_DIR/src/rmtn/rsm.parm  fort.50
ln -fs ./rsm_location                         fort.30
ln -fs /rhome/yeong/test/svrtest/gsm/bin/$PROG.x $PROG.x
./$PROG.x 1>$PROG.out 2>&1
if [ $? -ne 0 ] ; then
	echo "`date` $0: Execution failed." >>ERROR.out
	echo "`date` $0: Execution failed."
	exit 8
fi
