#!/bin/sh
#
# read initial time and make the boudary and forecast shels
#
PROG=nhm_read_date
rm fort.*
ln -fs ${RSIG_DIR}/r_sigit.ft00  fort.25
ln -fs ./idate.txt               fort.30
ln -fs /rhome/yeong/test/svrtest/gsm/bin/$PROG.x $PROG.x
./$PROG.x 1>$PROG.out 2>&1
if [ $? -ne 0 ] ; then
	echo "`date` $0: Execution failed." >>ERROR.out
	echo "`date` $0: Execution failed."
	exit 8
fi
