#!/bin/sh
#
# make Sib distribution file of rsm
#
PROG=nhm_sib_dep_veg_arg_rsm
rm fort.* 2>/dev/null
ln -fs ./flatflon_rsm.dat                fort.20
ln -fs ./rsm_geopt.dat                   fort.25
ln -fs /rhome/yeong/test/svrtest/libs/con/nhm/typ_cgcm3.ctl  fort.30
ln -fs /rhome/yeong/test/svrtest/libs/con/nhm/typ_cgcm3.gd   fort.35
ln -fs $OUTER_RSM_SRCS_DIR/define.h      fort.50
#
ln -fs /rhome/yeong/test/svrtest/gsm/bin/$PROG.x $PROG.x
./$PROG.x 1>$PROG.out 2>&1
if [ $? -ne 0 ] ; then
	echo "`date` $0: Execution failed." >>ERROR.out
	echo "`date` $0: Execution failed."
	exit 8
fi
