#!/bin/sh
if [ $# -ne 0 ] ; then
	echo $0:error in the number of arguments
	exit 8
fi
#
#  create ctl file for nc files
#
/rhome/yeong/test/svrtest/gsm_runs/runscr/roms_makectl `pwd`
#
#  input netcdf file description file
#
ln -fs /rhome/yeong/test/svrtest/libs/con/varinfo.dat .
#
PROG=roms
rm -f $PROG.x
ln -fs /rhome/yeong/test/svrtest/gsm/bin/${PROG}.x $PROG.x
