#!/bin/sh
#
#  Restart
#
#  Get fhour from sigit file and return its value
#
h=`/rhome/yeong/test/svrtest/libs/etc/fhour sigit`
h=`expr $h`
if [ $h -lt 10 ] ; then h=0$h ; fi
echo $h
echo "Restarting from $h" >>ERROR.out
